### PR TITLE
Upgrade laravel

### PR DESCRIPTION
**Pull request by well1791**
TODO:

- [x] Upgrade Laravel according to #6 
- [x] Solve issue #5

### CODE REVIEW

**Comment by mcpacific** [comment]
I implemented the latest changes and the only issue I found this time was the same error as before, but this time, right at the beginning of the CreateWorkspace command. In this function:

`    function createWorkspaceConfig()
    {
        $fileContent = File::get("resources/workspace.json");
        $interpolatedContent = sprintfn($fileContent, $this->argument());
        return json_decode($interpolatedContent);
    }`

Specifically, line 81 "$interpolatedContent = sprintfn($fileContent, $this->argument());" it seems that the sprintfn helper function incorrectly converts "https://" to "https:\". My doing a str_replace I was able to get the workspace to create without any errors.

**Comment by well1791** [comment]
Hey @mcpacific !

Thanks for taking a look at the repo and amazing job debugging the error!
Also, sorry for being idle so long. I've been quite busy from last week.

I'll update this repo so it applies the suggestions you mentioned, and I'll add more test coverage to that part.

Once again! thanks for sharing your solution!

**Comment by mcpacific** [comment]
Glad to help and no worries! I updated my code but now I get a different error:

` [Twilio\Exceptions\RestException]
[HTTP 400] Unable to create record: AssignmentCallbackUrl is not a valid URL: https10eca27.ngrok.io/assignment`

Since my first reply I've noticed that at the beginning of workspace:create it shows the host name incorrectly:

`- Server:       https:\b10eca27.ngrok.io`

So it seems the genesis for the error is actually the Laravel console command (input) at the very beginning. I'm not sure why it's not properly inserting the correct 'host' (it acts almost as if it's escaping the input, but not doing a good job of it!).

**Comment by well1791** [comment]
Weird stuff, I wasn't able to reproduce the error. Also, I haven't found anything related to this error in Laravel/issues.

Although upgrading this PR doesn't solve your problem, is still good to have the repo up to date with the latest version. So, I'll merge this PR as it doesn't break any existing feature.

Please, feel free to open issues if you still face errors with this repo.

**Comment by mcpacific** [comment]
Really is weird! I just cloned the Git again on my local PC and the same thing happened. I’m running PHP 7.1 on Windows 10. However, when I cloned the Git on my Linux server (Centos 7), it worked with no errors!

 

Mark

**Comment by well1791** [comment]
Yeah, I had a suspicion about your environment.

Usually, when it comes to windows nothing feels safe.

So, I think the best when working with PHP on windows (actually, on any platform) is to use [homestead](https://laravel.com/docs/5.5/homestead).

Hope that helps you in your future projects!

Cheers! 👋

**Pull request merged**
